# Generated by Django 4.1.7 on 2023-04-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_settings_alter_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
