# Generated by Django 4.1.7 on 2023-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_url', models.TextField()),
                ('cover_description', models.TextField()),
                ('cover_title', models.CharField(max_length=100)),
            ],
        ),
    ]
