# Generated by Django 4.1.7 on 2023-04-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_settings_options_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='specification',
            field=models.IntegerField(choices=[(1, 'Movies'), (2, 'Series'), (3, 'Trailers')], default=1),
        ),
    ]
